### ISSUE TITLE
Selfbot Rules

### ISSUE THREAD

**Issue by ConnerItayi** [Mydract/Discord-Server-Nuker#2]
Your wiki page is incorrect. As of now discords stance is that any and all Selfbots are a ToS violation. With that said, even if it weren't, this would be abuse of the API and would leave a user subject to ban anyways. You may as well just take down the "Selfbot Rules" page as this violates the ToS in numerous ways.

https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-

**Comment by AneiDoru** [comment]
On top of that, it gives everyone who downloads it malware. If they get infected, good. They deserve it.
